---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r}
setwd('/Users/yanglinjie/Downloads/Rep')
library(dplyr)
library(ggplot2)
```


## Loading and preprocessing the data
```{r}
activity <- read.csv("activity.csv")
act.complete <- na.omit(activity)
```



## What is mean total number of steps taken per day?

```{r}
act.day <- group_by(act.complete, date)
act.day <- summarize(act.day, steps=sum(steps))
```
```{r}
qplot(steps, data=act.day)
```
```{r}
mean(act.day$steps)
```
```{r}
median(act.day$steps)
```


## What is the average daily activity pattern?
```{r}
act.int <- group_by(act.complete, interval)
act.int <- summarize(act.int, steps=mean(steps))
```

```{r}
ggplot(act.int, aes(interval, steps)) + geom_line()
```

```{r}
act.int[act.int$steps==max(act.int$steps),]
```

## Imputing missing values
```{r}
nrow(activity)-nrow(act.complete)
```
```{r}
names(act.int)[2] <- "mean.steps"
act.impute <- merge(activity, act.int)
act.impute$steps[is.na(act.impute$steps)] <- act.impute$mean.steps[is.na(act.impute$steps)]
```

```{r}
act.impute$steps[is.na(act.impute$steps)] <- act.impute$mean.steps[is.na(act.impute$steps)]
act.day.imp <- group_by(act.impute, date)
act.day.imp <- summarize(act.day.imp, steps=sum(steps))
```
```{r}
qplot(steps, data=act.day.imp)
```
```{r}
mean(act.day.imp$steps)
median(act.day.imp$steps)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
act.impute$dayofweek <- weekdays(as.Date(act.impute$date))
act.impute$weekend <-as.factor(act.impute$dayofweek=="Saturday"|act.impute$dayofweek=="Sunday")
levels(act.impute$weekend) <- c("Weekday", "Weekend")
act.weekday <- act.impute[act.impute$weekend=="Weekday",]
act.weekend <- act.impute[act.impute$weekend=="Weekend",]
act.int.weekday <- group_by(act.weekday, interval)
act.int.weekday <- summarize(act.int.weekday, steps=mean(steps))
act.int.weekday$weekend <- "Weekday"
act.int.weekend <- group_by(act.weekend, interval)
act.int.weekend <- summarize(act.int.weekend, steps=mean(steps))
act.int.weekend$weekend <- "Weekend"
act.int <- rbind(act.int.weekday, act.int.weekend)
act.int$weekend <- as.factor(act.int$weekend)
ggplot(act.int, aes(interval, steps)) + geom_line() + facet_grid(weekend ~ .)
```

